#!/bin/bash
#
# Script to parse output generated by Ayaka from DTIStudio
#
# GS, April 2017

fname=$1;

header='';
eigval1='';
eigval2='';
eigval3='';
fa='';
trace='';

split -p "^[0-9]+" sub2Run2FA.txt

while read line; do
    # if it's a blank line, close the ROI data only if we haven't already
    # closed it
    if [ ${#line} == 1 ]; then
        last=$((${#header}));
        if [ ! ${header:$last:1} == ',' ]; then
            echo 'hello'
            header=$header',';
            eigval1='';
            eigval2='';
            eigval3='';
            fa='';
            trace='';
        fi;
    fi;
done < $fname

echo $header
